package sbst

import (
	"errors"
	"fmt"
	"math/big"

	"github.com/Nik-U/pbc"
)

var twoInv *big.Int
var lagrangeCache map[int][]*big.Int

// set/propagate/kill wrapper used in the
// CARRIES protocol
type spk struct {
	s, p, k *pbc.Element
}

// RandomShare returns a random encrypted integer
// in {1...pk.N}, jointly generated by all parties
func (mpc *MPC) RandomShare() *pbc.Element {

	// TODO: can be made concurrent
	share := mpc.Pk.EncryptElement(big.NewInt(0))
	for _, party := range mpc.Parties {
		share = mpc.Pk.EAddElements(share, party.getRandomShare())
	}

	return share
}

// RandomInvertibleShare returns a random encrypted integer
// in {1...pk.N} and its inverse (mod pk.T)
func (mpc *MPC) RandomInvertibleShare() (*pbc.Element, *pbc.Element, error) {

	a := mpc.RandomShare()
	b := mpc.RandomShare()
	c := mpc.DecryptElementMPC(mpc.Pk.EMultElements(a, b), true, false)

	if c.Int64() == 0 {
		return nil, nil, errors.New("abort")
	}

	cInv := big.NewInt(0).ModInverse(c, mpc.Pk.T)
	aInv := mpc.Pk.EMultCElement(b, cInv)

	return a, aInv, nil
}

// RandomBit returns a random bit from {0,1}
func (mpc *MPC) RandomBit() (*pbc.Element, error) {

	r := mpc.RandomShare()
	a := mpc.DecryptElementMPC(mpc.Pk.EMultElements(r, r), true, false)

	// zero won't work
	if a.Cmp(big.NewInt(0)) == 0 {
		return nil, errors.New("abort")
	}

	b := big.NewInt(0).ModSqrt(a, mpc.Pk.T)
	bInv := big.NewInt(0).ModInverse(b, mpc.Pk.T) // find b^-1 mod T

	twoInv = big.NewInt(0).ModInverse(big.NewInt(2), mpc.Pk.T) // find 2^-1 mod T

	c := mpc.Pk.EMultCElement(r, bInv)
	c = mpc.Pk.EAddElements(c, mpc.Pk.EncryptElement(big.NewInt(1)))
	c = mpc.Pk.EMultCElement(c, twoInv)

	return c, nil
}

// SolvedBits returns a random bit string from {0,1}^n and the corresponding
// integer value from {0...T}
func (mpc *MPC) SolvedBits() ([]*pbc.Element, *pbc.Element, error) {

	n := mpc.Pk.T.BitLen()
	bits := make([]*pbc.Element, n)

	for i := 0; i < n; i++ {
		bit, err := mpc.RandomBit()
		// err if protocol aborts; a low probability event
		for err != nil {
			bit, err = mpc.RandomBit()
		}

		bits[i] = bit
	}

	// largest value in bit form log(T) bits
	maxBits := mpc.EBitsBigEndian(mpc.Pk.T, n)

	// picked random bits should evaluate to less
	// than T otherwise no equivalent in integer space
	bad := mpc.EBitsLessThan(maxBits, bits)
	if mpc.DecryptElementMPC(bad, true, true).Int64() == 1 {
		fmt.Print("a_2 = ")
		for i := 0; i < len(bits); i++ {
			d := mpc.DecryptElementMPC(bits[len(bits)-i-1], false, true)
			fmt.Printf("%d", d)
		}
		fmt.Println()

		fmt.Print("max_2 = ")
		for i := 0; i < len(maxBits); i++ {
			d := mpc.DecryptElementMPC(maxBits[len(maxBits)-i-1], false, true)
			fmt.Printf("%d", d)
		}
		fmt.Println()

		return nil, nil, errors.New("abort")
	}

	// compute the represented integer
	val := mpc.Pk.EncryptElement(big.NewInt(0))
	pow := big.NewInt(1)
	for i := 0; i < len(bits); i++ {
		val = mpc.Pk.EAddElements(val, mpc.Pk.EMultCElement(bits[i], pow))
		pow = pow.Mul(pow, big.NewInt(2))
	}

	return bits, val, nil
}

// EBits returns a bit representation of an integer in {0...T}
func (mpc *MPC) EBits(a *pbc.Element) []*pbc.Element {

	n := mpc.Pk.T.BitLen() + 1

	// max value in integers < T
	maxValue := big.NewInt(0).Exp(big.NewInt(2), big.NewInt(int64(n)), nil)

	// max value in encrypted dummy bit form
	maxEBits := mpc.EBitsBigEndian(mpc.Pk.T, n)

	// diff 2^log(T) - T note that this has to be a positive quantity
	deltaBits := mpc.BitsBigEndian(big.NewInt(0).Sub(maxValue, mpc.Pk.T), n)

	// get solved bits
	solvedBits, d, err := mpc.SolvedBits()
	for err != nil {
		fmt.Println("[DEBUG]: SolvedBits() aborted.")
		solvedBits, d, err = mpc.SolvedBits()
	}

	// compute a-d where d is the integer returned from solvedbits
	rev := mpc.DecryptElementMPC(mpc.Pk.ESubElements(a, d), false, false)
	revBits := mpc.EBitsBigEndian(rev, n)
	sumBits := mpc.EBitsADD(revBits, solvedBits)

	q := mpc.ReEncryptElementMPC(mpc.EBitsLessThan(maxEBits, sumBits))
	g := make([]*pbc.Element, n)
	for i := 0; i < n; i++ {
		g[i] = mpc.Pk.EMultCElement(q, deltaBits[i])
	}

	h := mpc.EBitsADD(sumBits, g)

	// drop the two most significant bits to correct error
	// see paper for details
	return h[0 : len(h)-1]
}

// EFanInMULT efficiently computes [x,x^2,x^3...x^n] where n = len(elements)
// Note: can be used as a PrefixAND when elements are binary
func (mpc *MPC) EFanInMULT(elements []*pbc.Element) []*pbc.Element {

	n := len(elements)
	randomBits := make([]*pbc.Element, n+1)
	randomBitsInv := make([]*pbc.Element, n+1)

	// TODO: loop can be made parallel
	var err error
	for i := 0; i <= n; i++ {
		randomBits[i], randomBitsInv[i], err = mpc.RandomInvertibleShare()
		if err != nil {
			fmt.Println("[DEBUG]: RandomInvertibleShare() aborted.")
			randomBits[i], randomBitsInv[i], err = mpc.RandomInvertibleShare()
		}
	}

	res := make([]*pbc.Element, n)
	powerMult := elements[0]
	for i := 0; i < n; i++ {
		d := mpc.Pk.EMultElements(randomBits[i], powerMult)
		d = mpc.ReEncryptElementMPC(d)
		d = mpc.Pk.EMultElements(d, randomBitsInv[i+1])
		q := mpc.DecryptElementMPC(d, true, false)

		inv := mpc.Pk.EMultElements(randomBitsInv[i], randomBits[i+1])
		res[i] = mpc.ReEncryptElementMPC(mpc.Pk.EMultCElementL2(inv, q, true))

		// avoid unnecessary computation
		if i+1 < n {
			powerMult = mpc.Pk.EMultElements(powerMult, elements[i+1])
			powerMult = mpc.ReEncryptElementMPC(powerMult)
		}
	}

	return res
}

// EBitsOR computes the OR of all the bits
func (mpc *MPC) EBitsOR(bits []*pbc.Element) *pbc.Element {

	n := len(bits)
	poly := binaryORFunctionInterpolation(n, mpc.Pk.T)

	sum := mpc.Pk.EncryptElement(big.NewInt(1))
	for i := 0; i < n; i++ {
		sum = mpc.Pk.EAddElements(sum, bits[i])
	}

	a := make([]*pbc.Element, n+1)
	for i := 0; i <= n; i++ {
		a[i] = sum
	}

	a = mpc.EFanInMULT(a)

	res := mpc.Pk.EncryptElement(big.NewInt(0).Add(poly[n], big.NewInt(1)))
	for i := 1; i <= n; i++ {
		c := mpc.Pk.EMultCElement(a[i-1], poly[n-i])
		res = mpc.Pk.EAddElements(res, c)
	}

	return res
}

// EBitsAND computes the AND of all the bits
func (mpc *MPC) EBitsAND(bits []*pbc.Element) *pbc.Element {

	degree := len(bits)

	res := bits[0]
	for i := 1; i < degree; i++ {
		c := mpc.Pk.EMultElements(res, bits[i])
		res = mpc.ReEncryptElementMPC(c)
	}

	return res
}

func (mpc *MPC) EBitsPreOR(bits []*pbc.Element) []*pbc.Element {

	degree := len(bits)

	// TODO: process this loop in parallel
	res := make([]*pbc.Element, degree)
	for i := 1; i < degree; i++ {
		row := make([]*pbc.Element, i+1)
		for k := 0; k <= i; k++ {
			if k <= i {
				row[k] = bits[k]
			}
		}

		res[i] = mpc.EBitsOR(row)
	}

	res[0] = bits[0]
	return res
}

func (mpc *MPC) EBitsPrefixSPK(bits []*spk) []*spk {

	degree := len(bits)
	// TODO: process this loop in parallel
	res := make([]*spk, degree)
	for i := 0; i < degree; i++ {
		row := make([]*spk, i+1)
		for k := 0; k <= i; k++ {
			row[k] = bits[k]
		}

		res[i] = mpc.bitsSPK(row)
	}

	return res
}

func (mpc *MPC) EBitsADD(a, b []*pbc.Element) []*pbc.Element {

	if len(a) < len(b) {
		a = mpc.makeEqualLength(a, b)
	} else {
		b = mpc.makeEqualLength(b, a)
	}

	degree := len(a) // len(a) = len(b) now

	carries := mpc.EBitsCarries(a, b)

	sum := make([]*pbc.Element, degree)
	lsb := mpc.Pk.EAddElements(a[0], b[0])
	lsb = mpc.Pk.ESubElements(lsb, mpc.Pk.EMultCElement(carries[0], big.NewInt(2)))
	sum[0] = lsb
	sum[degree-1] = carries[degree-1]

	for i := 1; i < degree-1; i++ {
		sum[i] = mpc.Pk.EAddElements(a[i], b[i])
		sum[i] = mpc.Pk.EAddElements(sum[i], carries[i-1])
		sum[i] = mpc.Pk.ESubElements(sum[i], mpc.Pk.EMultCElement(carries[i], big.NewInt(2)))
	}

	return sum
}

func (mpc *MPC) EBitsLessThan(a, b []*pbc.Element) *pbc.Element {

	if len(a) < len(b) {
		a = mpc.makeEqualLength(a, b)
	} else {
		b = mpc.makeEqualLength(b, a)
	}

	degree := len(a) // len(a) = len(b) now
	e := make([]*pbc.Element, degree)

	for i := 0; i < degree; i++ {
		d := mpc.Pk.ESubElements(a[i], b[i])
		e[degree-i-1] = mpc.ReEncryptElementMPC(mpc.Pk.EMultElements(d, d))
	}

	f := mpc.EBitsPreOR(e)
	g := make([]*pbc.Element, degree)
	g[0] = f[0]
	for i := degree - 1; i > 0; i-- {
		g[i] = mpc.Pk.ESubElements(f[i], f[i-1])
	}

	h := make([]*pbc.Element, degree)
	for i := 0; i < degree; i++ {
		h[i] = mpc.Pk.EMultElements(g[degree-i-1], b[i])
	}

	res := mpc.Pk.ToDeterministicL2Element(mpc.Pk.EncryptElement(big.NewInt(0)))

	for i := 0; i < degree; i++ {
		res = mpc.Pk.EAddL2Elements(res, h[i])
	}

	return res
}

func (mpc *MPC) EBitsCarries(a, b []*pbc.Element) []*pbc.Element {

	if len(a) < len(b) {
		a = mpc.makeEqualLength(a, b)
	} else {
		b = mpc.makeEqualLength(b, a)
	}

	one := mpc.Pk.EncryptElement(big.NewInt(1))
	degree := len(a) // len(a) = len(b) now

	s := make([]*pbc.Element, degree)
	p := make([]*pbc.Element, degree)
	k := make([]*pbc.Element, degree)
	spks := make([]*spk, degree)

	// TODO: process this loop in parallel
	for i := 0; i < degree; i++ {
		c := mpc.Pk.EMultElements(a[i], b[i])
		s[i] = mpc.ReEncryptElementMPC(c)
	}

	for i := 0; i < degree; i++ {

		// compute propagate bit
		d := mpc.Pk.EAddElements(a[i], b[i])
		p[i] = mpc.Pk.ESubElements(d, mpc.Pk.EMultCElement(s[i], big.NewInt(2)))

		// compute kill bit
		d = mpc.Pk.EAddElements(s[i], p[i])
		k[i] = mpc.Pk.ESubElements(one, d)

		spks[i] = &spk{s: s[i], p: p[i], k: k[i]}
	}

	f := mpc.EBitsPrefixSPK(spks)

	res := make([]*pbc.Element, degree)

	for i := 0; i < degree; i++ {
		res[i] = f[i].s
	}

	return res
}

func (mpc *MPC) makeEqualLength(a, b []*pbc.Element) []*pbc.Element {
	zero := mpc.Pk.EncryptElement(big.NewInt(0))
	delta := len(b) - len(a)
	zeroArray := make([]*pbc.Element, delta)
	for i := 0; i < delta; i++ {
		zeroArray[i] = zero
	}

	return append(a, zeroArray...)
}

func (mpc *MPC) bitsSPK(tups []*spk) *spk {

	size := len(tups)

	b := tups[0].p
	for i := 1; i < size; i++ {
		c := mpc.Pk.EMultElements(b, tups[i].p) // equiv to AND operation
		b = mpc.ReEncryptElementMPC(c)
	}

	allPs := make([]*pbc.Element, size)
	for i := 0; i < size; i++ {
		allPs[i] = tups[size-i-1].p
	}

	preAnd := mpc.ReverseBits(mpc.EFanInMULT(allPs))

	carries := make([]*pbc.Element, size)
	carries[size-1] = mpc.Pk.ToDeterministicL2Element(tups[size-1].k)

	// TODO: process this loop in parallel
	for i := 0; i < size-1; i++ {
		q := mpc.Pk.EMultElements(tups[i].k, preAnd[i+1]) // equiv to AND operation
		carries[i] = q
	}

	zero := mpc.Pk.EncryptElement(big.NewInt(0))
	one := mpc.Pk.EncryptElement(big.NewInt(1))

	c := mpc.Pk.ToDeterministicL2Element(zero)
	for i := 0; i < size; i++ {
		c = mpc.Pk.EAddL2Elements(c, carries[i])
	}

	b = mpc.Pk.ToDeterministicL2Element(b)
	diff := mpc.Pk.EAddL2Elements(b, c)
	a := mpc.Pk.ESubL2Elements(mpc.Pk.ToDeterministicL2Element(one), diff)
	a = mpc.ReEncryptElementMPC(a)

	return &spk{s: a, p: b, k: c}
}

func (mpc *MPC) ReverseBits(bits []*pbc.Element) []*pbc.Element {

	size := len(bits)
	bitsR := make([]*pbc.Element, size)
	for i := 0; i < size; i++ {
		bitsR[size-i-1] = bits[i]
	}

	return bitsR
}

// BitsBigEndian returns the n-bit representation of an integer a
func (mpc *MPC) BitsBigEndian(a *big.Int, n int) []*big.Int {
	s := fmt.Sprintf("%b", a)
	bits := make([]*big.Int, len(s))
	k := 0
	for i := len(s) - 1; i >= 0; i-- {
		bits[k] = big.NewInt(int64(s[i] - '0'))
		k++
	}

	for i := n - len(s); i >= 0; i-- {
		bits = append(bits, big.NewInt(0))
	}

	return bits
}

// EBitsBigEndian returns the n-bit (encrypted) representation of an integer a
func (mpc *MPC) EBitsBigEndian(a *big.Int, n int) []*pbc.Element {
	s := fmt.Sprintf("%b", a)
	bits := make([]*pbc.Element, len(s))
	k := 0
	for i := len(s) - 1; i >= 0; i-- {
		bits[k] = mpc.Pk.EncryptElement(big.NewInt(int64(s[i] - '0')))
		k++
	}

	zero := mpc.Pk.EncryptDeterministic(big.NewInt(0))
	for i := n - len(s); i >= 0; i-- {
		bits = append(bits, zero)
	}

	return bits
}

// EBitsZero returns the n-bit vector of zeros
func (mpc *MPC) EBitsZero() []*pbc.Element {

	n := mpc.Pk.T.BitLen()
	bits := make([]*pbc.Element, n)
	zero := mpc.Pk.EncryptDeterministic(big.NewInt(0))

	for i := 0; i < n; i++ {
		bits[i] = zero
	}

	return bits
}

func neg(a *big.Int, p *big.Int) *big.Int {
	return big.NewInt(0).Sub(p, a)
}

// compute the lagrange interpolation of the function such that
// f(1) = 0, f(1) = f(2) = f(3).... = 1
func binaryORFunctionInterpolation(n int, p *big.Int) []*big.Int {

	var numerator []*big.Int
	var poly []*big.Int

	denom := big.NewInt(1)
	poly = make([]*big.Int, n)

	for k := 0; k < n; k++ {
		poly[k] = big.NewInt(0)
	}

	for i := 1; i <= n; i++ {
		for j := 0; j <= n; j++ {
			if i != j {
				xi := big.NewInt(int64(i + 1))
				xj := big.NewInt(int64(j + 1))

				if numerator == nil {
					numerator = []*big.Int{big.NewInt(1), neg(xi, p)}
				} else {
					numerator = polyMult(numerator, []*big.Int{big.NewInt(1), neg(xj, p)})
				}

				denom.Mul(denom, big.NewInt(0).Add(xi, neg(xj, p)))
			}
		}

		if big.NewInt(0).Abs(denom).Cmp(big.NewInt(1)) != 0 {
			denom = denom.ModInverse(denom, p)
		}

		for i := 0; i < len(numerator); i++ {
			numerator[i].Mul(numerator[i], denom)
		}

		poly = polyAdd(poly, numerator)

		// reset
		denom = big.NewInt(1)
		numerator = nil

	}

	for i := 0; i < len(poly); i++ {
		if poly[i].Cmp(big.NewInt(0)) < 0 {
			poly[i] = poly[i].Neg(poly[i])
			poly[i] = poly[i].Mod(poly[i], p)
			poly[i] = neg(poly[i], p)
		} else {
			poly[i] = poly[i].Mod(poly[i], p)
		}
	}

	return poly
}

func polyMult(poly1 []*big.Int, poly2 []*big.Int) []*big.Int {
	n := len(poly1) + len(poly2)
	result := make([]*big.Int, n)
	for k := 0; k < n; k++ {
		result[k] = big.NewInt(0)
	}

	for i, coefficient := range poly1 {
		for j, coefficient2 := range poly2 {
			result[i+j].Add(result[i+j], big.NewInt(0).Mul(coefficient, coefficient2))
		}
	}
	return result[0 : n-1]
}

func polyAdd(poly1 []*big.Int, poly2 []*big.Int) []*big.Int {
	len1 := len(poly1)
	len2 := len(poly2)

	result := make([]*big.Int, len1)

	if len1 >= len2 {
		for i := 0; i < len1-len2; i++ {
			result[i] = poly1[i]
		}

		k := 0
		for i := len1 - len2; i < len1; i++ {
			result[i] = big.NewInt(0).Add(poly1[i], poly2[k])
			k++
		}

	} else {
		result = polyAdd(poly2, poly1)
	}

	return result

}
